language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-28.0.3                # Build tools version
    - android-28                        # Target SDK version

jdk:
  - oraclejdk8

script:
  - ./gradlew build

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle